### ISSUE TITLE
User/Server Statistics

### ISSUE THREAD

**Issue by Log4Jake** [tkbstudios/netchat-server-rust#1]
**Add a sqldb or some method of storage similar that contains the following info.**

- Messages sent for the User
- Total messages sent to the server
- Active time for the user (time logged in)
- Active time for the server (total time server has been running, not to be confused with uptime)
- Server uptime (Time since it started last, Like a stopwatch, it might just be easier to log the time the server starts then handle a timer/stopwatch)
- List of all users who have logged in.
- Offline and Online statuses for all users who have logged in.
- Number of times users have logged in.

**Add an API to access this info in a JSON format. You can add an option in config.toml to enable the API and an option to open it to all users who authenticate to the API with their session and username**

Some API endpoint ideas.

- /api/v1/user/username/status  #Returns boolean 
- /api/v1/user/username/messagecount  #Returns total messages sent by the user
- /api/v1/user/username/totaltime  #Returns total amount of time the user has been logged in
- /api/v1/user/username/activetime  #Returns total amount of time the user has been logged in
- /api/v1/user/username/logincount  #Returns total logins of user
- /api/v1/sever/messagecount  #Returns total messages sent by all users
- /api/v1/sever/users  #Returns list of all users with statuses
- /api/v1/server/activetime  #Returns the total amount of time the server has ever been online
- /api/v1/server/uptime  #Returns the time since the server started and the time the server started

**Comment by tkbstudios** [comment]
YES so many routes 😭 
Anyway I'm cooking

**Comment by tkbstudios** [comment]
https://github.com/tkbstudios/netchat-server-rust/tree/web-ui

**Comment by tkbstudios** [comment]
PR: https://github.com/tkbstudios/netchat-server-rust/pull/3
